### ISSUE TITLE
Not an issue just wanted to give thanks

### ISSUE THREAD

**Issue by Movisivi** [alexmohr/keyboard-backlight#19]
Finally it turns off just like in Windows! All I had to do was change the /sys/class/leds line in kbd_backlight.cpp to point to the correct path (in my case it was /sys/class/leds/asus::kbd_backlight) and build it from source. SWWWWEEEEEETTTTTT

**Comment by alexmohr** [comment]
Glad it works for you. Btw you didn't have to change the source code as you can pass the device as command line parameter.
````
    -b set keyboard backlight device path
       defaults to /sys/class/leds/tpacpi::kbd_backlight/brightness
````

**Comment by Movisivi** [comment]
Yes I saw that info too late. Good to know for the next install! Do you know if this is future proof? Will it need to be rewritten at some point or is it like Windows and this'll work for 20 years

**Comment by alexmohr** [comment]
The sysfs is pretty stable at this point and will continue working in the foreseeable future. But who knows if it still works in 20 years, as it's a pretty long time
